on:
  pull_request:
    types: [opened, edited, reopened, synchronize, review_requested]
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: pytest --junitxml=report.xml  # fixed incorrect dash

  analysis:
    runs-on: ubuntu-latest
    needs: build  # corrected from "test"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Count lines of code with Cloc
        run: |
          sudo apt-get install -y cloc
          cloc src/ > cloc-report.txt
          cat cloc-report.txt

  review-check:
    runs-on: ubuntu-latest
    steps:
      - name: Code Review Check for develop
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.pull_request?.number;
            if (!prNumber) {
              core.setFailed("Pull Request number not found in context.");
              return;
            }

            try {
              const reviews = await github.rest.pulls.listReviews({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber
              });

              const approved = reviews.data.some(review => review.state === 'APPROVED');
              if (!approved) {
                console.log("Warning: Code review is not approved, but proceeding.");
              } else {
                console.log("Code review is approved.");
              }
            } catch (error) {
              core.setFailed(`Error fetching reviews: ${error.message}`);
            }

      - name: Запуск flake8 через Reviewdog
        uses: reviewdog/action-flake8@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error
      - name: Запуск Black через Reviewdog
        uses: reviewdog/action-black@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: info